language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: oDSxtp/LVZEJkGjFOuKel5bQ13ZZdTQ2MRf0vINBP2cN0Syu0wc17dR0QHLHssQO0aySJLpMSAsYftGGKyHUCT2eOVkAiosURHI24qSsWzhbKdIjecCNw7gRItbBPCIpHAZAkk2E5wx6iRsN5Mq2clGzbOMynlcGkehHJIHsjsRFUAJ7LYp3rwqNKYUUFZ2NuvBTNvwjXQyp/1W2MtP5uydYK0dxYcuNIVBb/34n9UWuygK8JAkFw8fMq4B/Ueg1L0UFWzlTKFeW51llZxTpZPzPEJ/Pg12y7e8q+Pg4tl7pb9VPLUdgKcZoLcGDlJuxE7FHObclDxQtcIKFqf/7XqTw6CLTVrQV02A5uYrjhd0WJyjXtx8Q8lXjGwAnqDkt5KWoCZvw6NAWqi2zlTDwY5BgvUXj1IBivS16TeMrRqrcUwHIs5nCmbT3gkb93mDBph7d4IwN+iwWP6e6OqD0oKmMRTAVhHG1fVhJpvNuHIogbZe0gEn2IhrQu6RT9Gfde7O8UUJ1F8ebafJ+hUdgcN+RtM8YJe/onmAtYxzrjQ2hkD6pfcfPDL52bGqLhJ/ZYgeUkqvak2TXXp6rJZbuBemGI+SATG9+JJF5Cl3hQiLszQ3QqC8Vap9zRbbVKNdEgaf2Ppyus2Ww7yDjpVUrsD6uMTe8HHZFv1C9AEgp82Q=
